services:
  web:
    build:
      context: ./django
    image: django-app
    container_name: web
    volumes:
      - ./django:/app
    env_file:
      - .env
    # Порти закоментовані, можна відкрити тільки для налагодження
    # ports:
    #   - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:  
    image: nginx:latest
    container_name: nginx 
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data: 
