applications:
  - name: django-db-secret
    namespace: default
    project: default
    source:
      repoURL: ${github_repo_url}
      path: modules/argo_cd/manifests
      targetRevision: ${github_branch}
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
