image:
  # repository: {{ .Values.ecr_repository_url }}
  repository: "882961642780.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-preart-18062025214500"
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000
  metricsPort: 8001

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db # Значення за замовчуванням, буде перезаписано ArgoCD
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd
