apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "django-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
{{- end }}

